// src/dummyData.js

export const dummyNewsData = [
    {
      id: 1,
      title: 'Breaking News: Major Tech Event Announced',
      description: 'A major tech event is being planned for next month in Silicon Valley. This event will feature some of the biggest names in the industry.',
      author: 'John Doe',
      source: 'Tech News Today',
      category: 'Technology',
      publishedAt: '2025-01-07T12:00:00Z',
      url: 'https://www.example.com/tech-event',
      imageUrl: 'https://via.placeholder.com/150',
    },
    {
      id: 2,
      title: 'Sports Update: Local Team Wins Championship',
      description: 'The local basketball team has won the championship, making history with their outstanding performance in the finals.',
      author: 'Jane Smith',
      source: 'Sports Daily',
      category: 'Sports',
      publishedAt: '2025-01-06T18:30:00Z',
      url: 'https://www.example.com/local-team-championship',
      imageUrl: 'https://via.placeholder.com/150',
    },
    {
      id: 3,
      title: 'Health News: New Breakthrough in Cancer Research',
      description: 'Researchers have made a major breakthrough in cancer treatment, potentially changing the landscape of healthcare.',
      author: 'Alice Brown',
      source: 'Health Weekly',
      category: 'Health',
      publishedAt: '2025-01-05T09:15:00Z',
      url: 'https://www.example.com/cancer-research-breakthrough',
      imageUrl: 'https://via.placeholder.com/150',
    },
    {
      id: 4,
      title: 'World News: Major Earthquake Strikes Japan',
      description: 'A devastating earthquake has struck Japan, causing massive damage in major cities.',
      author: 'Tom Green',
      source: 'Global News',
      category: 'World',
      publishedAt: '2025-01-04T14:00:00Z',
      url: 'https://www.example.com/earthquake-japan',
      imageUrl: 'https://via.placeholder.com/150',
    },
    {
      id: 5,
      title: 'Technology Update: New iPhone Released',
      description: 'Apple has announced the release of its latest iPhone, featuring groundbreaking technology and a new design.',
      author: 'Sally White',
      source: 'Tech World',
      category: 'Technology',
      publishedAt: '2025-01-03T17:00:00Z',
      url: 'https://www.example.com/new-iphone',
      imageUrl: 'https://via.placeholder.com/150',
    },
  ];
  